# Archivo: ~/ros2_ws/src/tutorial_pkg/config/slam_apartment.yaml
# CONFIGURACIÓN SLAM CORREGIDA

slam_toolbox:
  ros__parameters:
    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    use_sim_time: true

    # General Parameters
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 2.0
    resolution: 0.05
    max_laser_range: 3.5
    minimum_time_interval: 0.3
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000

    # Correlation Parameters - VALORES CORREGIDOS
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.02  # CORREGIDO: era 0.1, debe estar entre 0.005-0.1

    # Loop Closure Parameters
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_response_coarse: 0.35
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_fine: 0.45
    loop_match_maximum_variance_fine: 0.012
    update_min_score: 0.4
    update_min_angle: 0.5
    update_min_distance: 0.2

    # Scan Matcher Parameters
    distance_variance_penalty: 0.3
    angle_variance_penalty: 0.8
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.7
    minimum_distance_penalty: 0.3
    use_response_expansion: true

    # PARÁMETROS ADICIONALES NECESARIOS PARA EXPLORACIÓN
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    
    # Optimización para apartamento
    loop_search_space_dimension: 8.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35