# Configuración CORREGIDA para exploración robusta
# config/explore_fixed.yaml

amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.1
    alpha2: 0.1
    alpha3: 0.1
    alpha4: 0.1
    alpha5: 0.1
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.3
    beam_skip_error_threshold: 0.8
    beam_skip_threshold: 0.2
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 3.5
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 300  # REDUCIDO para mejor rendimiento
    min_particles: 50
    odom_frame_id: "odom"
    pf_err: 0.03  # MÁS ESTRICTO
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.15  # REDUCIDO
    tf_broadcast: true
    transform_tolerance: 0.5  # MÁS TOLERANTE
    update_min_a: 0.15
    update_min_d: 0.1   # MÁS SENSIBLE
    z_hit: 0.6
    z_max: 0.05
    z_rand: 0.35
    z_short: 0.05
    scan_topic: scan
    map_topic: map

# CONFIGURACIÓN CRÍTICA PARA EXPLORACIÓN SIN OBSTÁCULOS FANTASMA
explore_node:
  ros__parameters:
    use_sim_time: True
    robot_base_frame: base_footprint
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: /global_costmap/costmap_updates
    visualize: true
    planner_frequency: 2.0                    # AUMENTADO - replanifica más frecuente
    progress_timeout: 10.0                    # REDUCIDO - menos paciencia
    potential_scale: 0.5                      # REDUCIDO - menos conservador
    orientation_scale: 0.1                    # REDUCIDO
    gain_scale: 3.0                           # AUMENTADO - busca fronteras más agresivamente
    transform_tolerance: 0.5
    min_frontier_size: 0.1                    # MUY REDUCIDO - acepta fronteras pequeñas
    frontier_travel_point: "closest"          # CAMBIADO - va al punto más cercano
    stop_on_failure: false
    explore_clear_costmaps: true              # NUEVO - limpia costmaps automáticamente

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 600.0      # REDUCIDO
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator/NavigateThroughPosesNavigator"

# CONTROLADOR MÁS AGRESIVO Y TOLERANTE
controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 25.0               # AUMENTADO
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.8                   # MÁS TOLERANTE
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2         # REDUCIDO
      movement_time_allowance: 20.0         # AUMENTADO - más paciencia

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.3                # MÁS TOLERANTE
      yaw_goal_tolerance: 0.3               # MÁS TOLERANTE
      stateful: True

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5               # AUMENTADO
      lookahead_dist: 0.8                   # AUMENTADO
      min_lookahead_dist: 0.4
      max_lookahead_dist: 1.5
      lookahead_time: 1.8
      rotate_to_heading_angular_vel: 2.0
      transform_tolerance: 0.2              # MÁS TOLERANTE
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.03    # REDUCIDO
      approach_velocity_scaling_dist: 1.0
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 2.0  # AUMENTADO
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: true  # HABILITADO
      regulated_linear_scaling_min_radius: 1.2
      regulated_linear_scaling_min_speed: 0.2
      allow_reversing: true                 # HABILITADO para maniobras
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.5      # REDUCIDO
      max_angular_accel: 4.0                # AUMENTADO
      max_robot_pose_search_dist: 15.0      # AUMENTADO
      use_interpolation: true
      cost_scaling_dist: 0.3                # NUEVO - escala costos
      cost_scaling_gain: 2.0                # NUEVO

# COSTMAP LOCAL MÁS AGRESIVO
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 15.0                # AUMENTADO
      publish_frequency: 8.0                # AUMENTADO
      global_frame: odom
      robot_base_frame: base_footprint
      width: 6                              # AUMENTADO
      height: 6                             # AUMENTADO
      resolution: 0.05
      rolling_window: true
      plugins: ["voxel_layer", "inflation_layer"]
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.5            # REDUCIDO - menos inflación
        inflation_radius: 0.25              # MUY REDUCIDO
        inflate_unknown: false              # NUEVO - no infla desconocido
        
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        footprint_clearing_enabled: true    # NUEVO
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.5
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5           # REDUCIDO
          obstacle_min_range: 0.0
          clear_on_max_reading: true        # NUEVO - limpia en lecturas máximas
      always_send_full_costmap: True

# COSTMAP GLOBAL OPTIMIZADO PARA EXPLORACIÓN COMPLETA
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 3.0                 # AUMENTADO
      publish_frequency: 3.0                # AUMENTADO
      global_frame: map
      robot_base_frame: base_footprint
      resolution: 0.05
      track_unknown_space: true             # CRÍTICO
      rolling_window: false
      width: 100                            # AUMENTADO para espacios grandes
      height: 100                           # AUMENTADO
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        footprint_clearing_enabled: true    # NUEVO
        max_obstacle_height: 2.0
        combination_method: 1               # MÁXIMO
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.5
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5           # REDUCIDO
          obstacle_min_range: 0.0
          inf_is_valid: true
          clear_on_max_reading: true        # NUEVO
          
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.0            # MUY REDUCIDO
        inflation_radius: 0.2               # MUY REDUCIDO
        inflate_unknown: false              # NO inflar espacios desconocidos
        inflate_around_unknown: false       # NUEVO
        
      always_send_full_costmap: True

# PLANIFICADOR MÁS TOLERANTE
planner_server:
  ros__parameters:
    use_sim_time: True
    expected_planner_frequency: 25.0        # AUMENTADO
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5                        # MÁS TOLERANTE
      use_astar: false                      # DIJKSTRA para mejor exploración
      allow_unknown: true                   # CRÍTICO
      use_final_approach_orientation: false # NUEVO - más flexible
      
# COMPORTAMIENTOS MÁS DINÁMICOS
behavior_server:
  ros__parameters:
    use_sim_time: True
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 15.0                   # AUMENTADO
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    
    spin:
      plugin: "nav2_behaviors/Spin"
      simulate_ahead_time: 1.0              # REDUCIDO
      max_rotational_vel: 2.0               # AUMENTADO
      min_rotational_vel: 0.6
      rotational_acc_lim: 5.0               # AUMENTADO
      
    backup:
      plugin: "nav2_behaviors/BackUp"
      backup_dist: 0.3                      # AUMENTADO
      backup_speed: 0.15                    # AUMENTADO
      time_allowance: 8.0                   # AUMENTADO
      
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
      
    wait:
      plugin: "nav2_behaviors/Wait"
      
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
      
    global_frame: odom
    robot_base_frame: base_footprint
    transform_tolerance: 0.2
    simulate_ahead_time: 1.5                # REDUCIDO
    max_rotational_vel: 2.0                 # AUMENTADO
    min_rotational_vel: 0.6
    rotational_acc_lim: 5.0                 # AUMENTADO

# SUAVIZADOR OPTIMIZADO
velocity_smoother:
  ros__parameters:
    use_sim_time: True
    smoothing_frequency: 25.0               # AUMENTADO
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 2.0]          # AUMENTADO
    min_velocity: [-0.5, 0.0, -2.0]        # AUMENTADO  
    max_accel: [3.0, 0.0, 5.0]             # AUMENTADO
    max_decel: [-3.0, 0.0, -5.0]           # AUMENTADO
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.5                   # AUMENTADO