# Configuración optimizada para exploración con TurtleBot3
# config/explore_optimized.yaml
amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 3.5
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 500
    min_particles: 50
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.15
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    map_topic: map

# CONFIGURACIÓN CRÍTICA PARA EXPLORACIÓN CONTINUA
explore_node:
  ros__parameters:
    use_sim_time: True
    robot_base_frame: base_footprint
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: /global_costmap/costmap_updates
    visualize: true
    planner_frequency: 1.0              # AUMENTADO - más frecuente
    progress_timeout: 15.0              # REDUCIDO - menos tiempo de espera
    potential_scale: 1.0                # REDUCIDO - más sensible a fronteras
    orientation_scale: 0.2              # AÑADIDO - considera orientación
    gain_scale: 2.0                     # AUMENTADO - prioriza fronteras grandes
    transform_tolerance: 0.3
    min_frontier_size: 0.15             # CRÍTICO - fronteras más pequeñas
    # Nuevos parámetros para mejor exploración
    frontier_travel_point: "middle"     # Ir al medio de fronteras
    stop_on_failure: false             # No parar en fallos
    

# Configuración del behavior tree navigator
bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator/NavigateThroughPosesNavigator"

# CONTROLADOR OPTIMIZADO PARA EXPLORACIÓN
controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0          # AUMENTADO
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.5              # MÁS TOLERANTE
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3      # REDUCIDO
      movement_time_allowance: 15.0      # AUMENTADO

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25            # MÁS TOLERANTE
      yaw_goal_tolerance: 0.25           # MÁS TOLERANTE
      stateful: True

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.4            # AUMENTADO
      lookahead_dist: 0.6                # AUMENTADO
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.2            # AUMENTADO
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.8
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: true    # HABILITADO
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 0.8        # AUMENTADO
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      allow_reversing: false
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 3.2
      max_robot_pose_search_dist: 10.0
      use_interpolation: true

# Costmap local optimizado
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 10.0             # AUMENTADO
      publish_frequency: 5.0             # AUMENTADO
      global_frame: odom
      robot_base_frame: base_footprint
      width: 5                           # AUMENTADO
      height: 5                          # AUMENTADO
      resolution: 0.05
      rolling_window: true
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.45          # REDUCIDO
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.5       # AUMENTADO - usa todo el rango
          raytrace_min_range: 0.0
          obstacle_max_range: 3.0       # AUMENTADO - detecta obstáculos más lejos
          obstacle_min_range: 0.0
      always_send_full_costmap: True

# COSTMAP GLOBAL CRÍTICO PARA EXPLORACIÓN
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 2.0              # AUMENTADO
      publish_frequency: 2.0             # AUMENTADO
      global_frame: map
      robot_base_frame: base_footprint
      resolution: 0.05
      track_unknown_space: true          # CRÍTICO para exploración
      rolling_window: false              # IMPORTANTE para mapa global
      width: 50                          # Tamaño fijo grande
      height: 50
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.5       # CRÍTICO - rango completo
          raytrace_min_range: 0.0
          obstacle_max_range: 3.0        # AUMENTADO
          obstacle_min_range: 0.0
          inf_is_valid: true             # IMPORTANTE para espacios infinitos
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0         # REDUCIDO - menos inflación
        inflation_radius: 0.45           # REDUCIDO
      always_send_full_costmap: True

# Planificador optimizado
planner_server:
  ros__parameters:
    use_sim_time: True
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.3                     # MÁS TOLERANTE
      use_astar: true                    # CAMBIADO - mejor para exploración
      allow_unknown: true                # CRÍTICO para exploración

# Servidor de comportamientos
behavior_server:
  ros__parameters:
    use_sim_time: True
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: odom
    robot_base_frame: base_footprint
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

# Suavizador de velocidad
velocity_smoother:
  ros__parameters:
    use_sim_time: True
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.4, 0.0, 1.0]       # AUMENTADO
    min_velocity: [-0.4, 0.0, -1.0]     # AUMENTADO
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0