# config/navigation_robust.yaml
# Configuración optimizada para exploración robusta sin falsos obstáculos

# AMCL - Localización más robusta
amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.1          # REDUCIDO - menos ruido en odometría
    alpha2: 0.1
    alpha3: 0.1
    alpha4: 0.1
    alpha5: 0.1
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.5      # AUMENTADO
    laser_max_range: 3.5
    laser_min_range: 0.0                # CAMBIADO de -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 300                  # REDUCIDO - mejor rendimiento
    min_particles: 50
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.1            # AUMENTADO - recuperación más rápida
    recovery_alpha_slow: 0.001          # AUMENTADO
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.15                     # REDUCIDO - menos incertidumbre
    tf_broadcast: true
    transform_tolerance: 2.0            # AUMENTADO - más tolerante
    update_min_a: 0.15                  # REDUCIDO
    update_min_d: 0.1                   # REDUCIDO
    z_hit: 0.6                          # AUMENTADO
    z_max: 0.05
    z_rand: 0.25                        # REDUCIDO
    z_short: 0.1                        # AUMENTADO

# EXPLORACIÓN MEJORADA
explore_node:
  ros__parameters:
    use_sim_time: True
    robot_base_frame: base_footprint
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: /global_costmap/costmap_updates
    visualize: true
    planner_frequency: 0.5              # REDUCIDO - menos agresivo
    progress_timeout: 30.0              # AUMENTADO - más paciencia
    potential_scale: 3.0                # AUMENTADO - mayor atracción a fronteras
    orientation_scale: 0.0              # DESHABILITADO - simplificar
    gain_scale: 1.0                     # REDUCIDO
    transform_tolerance: 1.0            # AUMENTADO
    min_frontier_size: 0.5              # AUMENTADO - fronteras más grandes
    frontier_travel_point: "centroid"   # CAMBIADO - mejor punto de destino
    stop_on_failure: false

# BEHAVIOR TREE NAVIGATOR
bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator/NavigateThroughPosesNavigator"
    # BT XML personalizado para exploración robusta
    default_nav_to_pose_bt_xml: |
      <root main_tree_to_execute="MainTree">
        <BehaviorTree ID="MainTree">
          <PipelineSequence name="NavigateWithRecovery">
            <RateController hz="1.0">
              <RecoveryNode number_of_retries="6" name="NavigateRecovery">
                <PipelineSequence name="NavigateWithReplanning">
                  <RateController hz="1.0">
                    <RecoveryNode number_of_retries="1" name="ComputePathToPose">
                      <ComputePathToPose goal="{goal}" path="{path}" planner_id="GridBased"/>
                      <ReactiveFallback name="ComputePathRecoveryFallback">
                        <GoalUpdated/>
                        <ClearEntireCostmap name="ClearGlobalCostmap-Context" service_name="global_costmap/clear_entirely_global_costmap"/>
                      </ReactiveFallback>
                    </RecoveryNode>
                  </RateController>
                  <RecoveryNode number_of_retries="1" name="FollowPath">
                    <FollowPath path="{path}" controller_id="FollowPath"/>
                    <ReactiveFallback name="FollowPathRecoveryFallback">
                      <GoalUpdated/>
                      <ClearEntireCostmap name="ClearLocalCostmap-Context" service_name="local_costmap/clear_entirely_local_costmap"/>
                    </ReactiveFallback>
                  </RecoveryNode>
                </PipelineSequence>
                <ReactiveFallback name="RecoveryFallback">
                  <GoalUpdated/>
                  <RoundRobin name="RecoveryActions">
                    <Sequence name="ClearingActions">
                      <ClearEntireCostmap name="ClearLocalCostmap-Sequence" service_name="local_costmap/clear_entirely_local_costmap"/>
                      <ClearEntireCostmap name="ClearGlobalCostmap-Sequence" service_name="global_costmap/clear_entirely_global_costmap"/>
                    </Sequence>
                    <Spin spin_dist="1.57"/>
                    <Wait wait_duration="5"/>
                    <BackUp backup_dist="0.15" backup_speed="0.025"/>
                  </RoundRobin>
                </ReactiveFallback>
              </RecoveryNode>
            </RateController>
          </PipelineSequence>
        </BehaviorTree>
      </root>

# CONTROLADOR MEJORADO
controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 10.0          # REDUCIDO - más estable
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.8              # AUMENTADO - más tolerante
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2      # REDUCIDO
      movement_time_allowance: 20.0      # AUMENTADO

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5             # AUMENTADO - más tolerante
      yaw_goal_tolerance: 0.5            # AUMENTADO
      stateful: True

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.3            # REDUCIDO - más conservador
      lookahead_dist: 0.8
      min_lookahead_dist: 0.4
      max_lookahead_dist: 1.5
      lookahead_time: 2.0                # AUMENTADO
      rotate_to_heading_angular_vel: 1.0  # REDUCIDO
      transform_tolerance: 0.5           # AUMENTADO
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 1.2
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 2.0  # AUMENTADO
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: true  # HABILITADO
      regulated_linear_scaling_min_radius: 1.2          # AUMENTADO
      regulated_linear_scaling_min_speed: 0.15          # REDUCIDO
      cost_scaling_dist: 1.0                           # NUEVO
      cost_scaling_gain: 1.0                           # NUEVO
      inflation_cost_scaling_factor: 10.0              # NUEVO
      allow_reversing: false
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 2.0             # REDUCIDO
      max_robot_pose_search_dist: 10.0
      use_interpolation: false           # DESHABILITADO para mejor estabilidad

# COSTMAP LOCAL OPTIMIZADO
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 5.0              # REDUCIDO
      publish_frequency: 2.0             # REDUCIDO
      global_frame: odom
      robot_base_frame: base_footprint
      width: 6                           # AUMENTADO
      height: 6                          # AUMENTADO
      resolution: 0.05
      rolling_window: true
      plugins: ["voxel_layer", "inflation_layer"]
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0         # REDUCIDO - menos inflación
        inflation_radius: 0.3            # REDUCIDO - menos hinchado
        inflate_unknown: false           # NUEVO - no inflar desconocido
        inflate_around_unknown: false    # NUEVO
        
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False         # DESHABILITADO - mejor rendimiento
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0        # REDUCIDO
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5        # REDUCIDO
          obstacle_min_range: 0.0
          inf_is_valid: false            # CAMBIADO
          
      always_send_full_costmap: False    # CAMBIADO

# COSTMAP GLOBAL MEJORADO
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 1.0              # REDUCIDO
      publish_frequency: 0.5             # REDUCIDO
      global_frame: map
      robot_base_frame: base_footprint
      resolution: 0.05
      track_unknown_space: true
      rolling_window: false
      width: 100                         # AUMENTADO para espacios grandes
      height: 100
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        footprint_clearing_enabled: true  # NUEVO
        max_obstacle_height: 2.0
        combination_method: 1             # NUEVO - máximo
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0        # REDUCIDO
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5        # REDUCIDO
          obstacle_min_range: 0.0
          inf_is_valid: false
          
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        subscribe_to_updates: True       # NUEVO
        
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.5         # REDUCIDO
        inflation_radius: 0.25           # REDUCIDO significativamente
        inflate_unknown: false           # NUEVO
        inflate_around_unknown: false    # NUEVO
        
      always_send_full_costmap: False    # CAMBIADO

# PLANIFICADOR ROBUSTO
planner_server:
  ros__parameters:
    use_sim_time: True
    expected_planner_frequency: 5.0     # REDUCIDO
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5                    # AUMENTADO
      use_astar: false                  # CAMBIADO a Dijkstra - más robusto
      allow_unknown: true
      use_final_approach_orientation: false  # NUEVO
      
# COMPORTAMIENTOS DE RECUPERACIÓN
behavior_server:
  ros__parameters:
    use_sim_time: True
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    
    spin:
      plugin: "nav2_behaviors/Spin"
      simulate_ahead_time: 2.0
      max_rotational_vel: 0.8           # REDUCIDO
      min_rotational_vel: 0.2           # REDUCIDO
      rotational_acc_lim: 2.0           # REDUCIDO
      
    backup:
      plugin: "nav2_behaviors/BackUp"
      simulate_ahead_time: 2.0
      backup_speed: 0.1                 # REDUCIDO
      time_allowance: 10.0              # AUMENTADO
      
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
      simulate_ahead_time: 2.0
      speed: 0.2                        # REDUCIDO
      time_allowance: 10.0              # AUMENTADO
      
    wait:
      plugin: "nav2_behaviors/Wait"
      
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
      
    global_frame: odom
    robot_base_frame: base_footprint
    transform_tolerance: 0.5            # AUMENTADO

# SUAVIZADOR DE VELOCIDAD
velocity_smoother:
  ros__parameters:
    use_sim_time: True
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.3, 0.0, 0.8]       # REDUCIDO
    min_velocity: [-0.3, 0.0, -0.8]     # REDUCIDO  
    max_accel: [1.5, 0.0, 2.0]          # REDUCIDO
    max_decel: [-1.5, 0.0, -2.0]        # REDUCIDO
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

# COLLISION MONITOR (NUEVO)
collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.5
    source_timeout: 5.0
    stop_pub_timeout: 2.0
    polygons: ["FootprintApproach"]
    observation_sources: ["scan"]
    
    FootprintApproach:
      type: "circle"
      radius: 0.3
      action_type: "slowdown"
      slowdown_ratio: 0.3
      linear_limit: 0.1
      angular_limit: 0.3
      
    scan:
      type: "scan"
      topic: "/scan"
      min_height: 0.05
      max_height: 2.0