# Archivo: ~/ros2_ws/src/tutorial_pkg/config/salon_explore.yaml

# Configuración optimizada para exploración en salón personalizado
amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0  # Aumentado para salón más grande
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 500     # Más partículas para espacio mayor
    min_particles: 100
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.15     # Menos sensible para espacios grandes
    update_min_d: 0.2
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

explore_node:
  ros__parameters:
    use_sim_time: True
    robot_base_frame: base_footprint
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: /global_costmap/costmap_updates
    visualize: true
    planner_frequency: 1.0           # Más frecuente para detectar fronteras
    progress_timeout: 60.0           # Timeout más largo
    potential_scale: 3.0             # Aumentar para mejor detección
    orientation_scale: 0.0
    gain_scale: 1.0
    transform_tolerance: 0.3
    min_frontier_size: 0.2           # Fronteras más pequeñas
    max_frontier_size: 5.0           # Permitir fronteras más grandes
    
    # NUEVOS PARÁMETROS CRÍTICOS
    frontier_travel_point: middle    # Ir al centro de la frontera
    explore_clear_space: true        # Explorar espacios libres
    min_frontier_cluster_size: 1     # Clusters mínimos de fronteras
    
    # Parámetros de reinicio automático
    recovery_behavior: true          # Habilitar comportamientos de recuperación
    stuck_timeout: 30.0              # Tiempo antes de considerar "atascado"
    rotate_recovery: true            # Rotar si se atasca
    backup_recovery: true            # Retroceder si se atasca

# Configuración mejorada del planificador
planner_server:
  ros__parameters:
    use_sim_time: True
    expected_planner_frequency: 10.0  # Reducir frecuencia para estabilidad
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5                  # Mayor tolerancia
      use_astar: true
      allow_unknown: true             # CRÍTICO: permitir navegación en zonas desconocidas
      use_final_approach_orientation: false

# Mejorar el controlador para exploración
controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 10.0        # Reducir para mayor estabilidad
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.5            # Mayor tolerancia a fallos
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5   # Mayor radio de movimiento
      movement_time_allowance: 30.0   # Más tiempo permitido

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.3          # Mayor tolerancia de posición
      yaw_goal_tolerance: 0.3         # Mayor tolerancia de orientación
      stateful: True

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.3         # Velocidad ligeramente mayor
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 1.0
      lookahead_time: 2.0
      rotate_to_heading_angular_vel: 0.8
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.1
      approach_velocity_scaling_dist: 0.6
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 2.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.7
      regulated_linear_scaling_min_speed: 0.2
      allow_reversing: false
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.5
      max_angular_accel: 1.5
      max_robot_pose_search_dist: 15.0
      use_interpolation: true

# Costmap local para salón
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 3.0        # Reducir frecuencia
      publish_frequency: 1.0
      global_frame: odom
      robot_base_frame: base_footprint
      width: 4                     # Aumentar tamaño
      height: 4
      resolution: 0.1              # Reducir resolución
      rolling_window: true
      plugins: ["voxel_layer", "inflation_layer"]
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0   # Reducir inflación
        inflation_radius: 0.4      # Reducir radio
        
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.1
        z_voxels: 10
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 4.0   # Aumentar rango
          raytrace_min_range: 0.0
          obstacle_max_range: 3.0   # Aumentar rango
          obstacle_min_range: 0.0
      always_send_full_costmap: True

# Costmap global para salón
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      update_frequency: 2.0           # Más frecuente
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      resolution: 0.05
      track_unknown_space: true       # CRÍTICO: seguir espacios desconocidos
      rolling_window: false           # No usar ventana deslizante en global
      width: 20                       # Aumentar tamaño del costmap
      height: 20
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.5      # Aumentar rango
          raytrace_min_range: 0.0
          obstacle_max_range: 3.0      # Aumentar rango
          obstacle_min_range: 0.0
          
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0      # Reducir inflación
        inflation_radius: 0.3         # Menor radio para permitir paso
        
      always_send_full_costmap: True
      
# Suavizador de velocidad para salón
velocity_smoother:
  ros__parameters:
    use_sim_time: True
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 1.0]    # Velocidades mayores
    min_velocity: [-0.5, 0.0, -1.0]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

# Configuración de comportamientos de recuperación
behavior_server:
  ros__parameters:
    use_sim_time: True
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    
    spin:
      plugin: "nav2_behaviors/Spin"
      simulate_ahead_time: 2.0
      max_rotational_vel: 1.0
      min_rotational_vel: 0.4
      rotational_acc_lim: 3.14
      
    backup:
      plugin: "nav2_behaviors/BackUp"
      simulate_ahead_time: 2.0
      backup_speed: 0.2
      backup_distance: 0.5
      time_allowance: 10.0
      
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
      simulate_ahead_time: 2.0
      max_linear_vel: 0.3
      min_linear_vel: 0.1
      max_angular_vel: 1.0
      
    wait:
      plugin: "nav2_behaviors/Wait"
      
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
      
    global_frame: odom
    robot_base_frame: base_footprint
    transform_tolerance: 0.2
    simulate_ahead_time: 3.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.14