# Archivo: ~/ros2_ws/src/tutorial_pkg/config/slam_apartment.yaml

# Configuración SLAM optimizada para apartamento de 10x10m
slam_toolbox:
  ros__parameters:
    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    use_sim_time: true

    # General Parameters
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 3.5        # Ajustado para el tamaño del apartamento
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000

    # Correlation Parameters - Optimizado para interiores
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Loop Closure Parameters - Ajustado para apartamento
    loop_search_maximum_distance: 3.0     # Menor distancia para espacios pequeños
    do_loop_closing: true
    loop_match_minimum_response_coarse: 0.35
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_fine: 0.45
    loop_match_maximum_variance_fine: 0.012
    update_min_score: 0.4
    update_min_angle: 0.9
    update_min_distance: 0.4               # Menor distancia mínima para apartamento

    # Scan Matcher Parameters - Optimizado para muebles y paredes
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349     # 0.2 degrees
    coarse_search_angle_offset: 0.349     # 20 degrees
    coarse_angle_resolution: 0.0349       # 2 degrees
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true