# config/slam_optimized.yaml
slam:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters - Optimizado para exploración continua
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 1.0            # MÁS FRECUENTE
    resolution: 0.05
    max_laser_range: 3.5                # RANGO COMPLETO
    minimum_time_interval: 0.05         # REDUCIDO - mapeado más frecuente
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # General Parameters - Optimizado para espacios abiertos
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1       # REDUCIDO - mapea más frecuentemente
    minimum_travel_heading: 0.15       # REDUCIDO - más sensible a rotación
    scan_buffer_size: 20               # AUMENTADO
    scan_buffer_maximum_scan_distance: 25.0  # AUMENTADO
    link_match_minimum_response_fine: 0.1    # REDUCIDO - menos restrictivo
    link_scan_maximum_distance: 2.0         # AUMENTADO
    loop_search_maximum_distance: 4.0       # AUMENTADO
    do_loop_closing: true
    loop_match_minimum_chain_size: 8        # REDUCIDO
    loop_match_maximum_variance_coarse: 4.0  # AUMENTADO
    loop_match_minimum_response_coarse: 0.25 # REDUCIDO
    loop_match_minimum_response_fine: 0.35   # REDUCIDO

    # Correlation Parameters - Más agresivos
    correlation_search_space_dimension: 0.4  # AUMENTADO
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.15  # AUMENTADO

    # Loop Closure Parameters - Más amplios
    loop_search_space_dimension: 10.0       # AUMENTADO
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.05 # AUMENTADO

    # Scan Matcher Parameters - Menos restrictivos
    distance_variance_penalty: 0.3          # REDUCIDO
    angle_variance_penalty: 0.8             # REDUCIDO
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.7             # REDUCIDO
    minimum_distance_penalty: 0.3          # REDUCIDO
    use_response_expansion: true